
import re
import os
import json
import time
import feedparser
import asyncio
from datetime import datetime, timedelta, timezone
from pathlib import Path
from google import genai
from google.api_core import exceptions
from dotenv import load_dotenv
from database import insert_daily_score, insert_headlines

load_dotenv()

# ─── Configure Gemini ────────────────────────────────────────────────────────
GEMINI_KEY = os.getenv("GEMINI_API_KEY", "")
client = genai.Client(api_key=GEMINI_KEY) if GEMINI_KEY else None

# ─── Cache ───────────────────────────────────────────────────────────────────
CACHE_FILE = Path(__file__).parent / "mood_cache.json"
UPDATE_INTERVAL = 10 * 60  # 10 minutes
CUTOFF_DAYS = 2  # Only consider news from the last 2 days
LLM = "gemini-3.1-flash-lite-preview"  # Use a lighter model for faster responses and less rate limiting


def load_cache() -> dict:
    try:
        if CACHE_FILE.exists():
            return json.loads(CACHE_FILE.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"[Cache read error] {e}")
    return {}


def save_cache(data: dict) -> None:
    try:
        data["saved_at"] = time.time()
        CACHE_FILE.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"[{datetime.now().isoformat()}] Cache updated successfully.", flush=True)
    except Exception as e:
        print(f"[Cache write error] {e}")


# ─── RSS Feeds ───────────────────────────────────────────────────────────────
RSS_FEEDS = {
    "Ynet": "https://www.ynet.co.il/Integration/StoryRss2.xml",
    "Walla": "https://rss.walla.co.il/feed/22",
    "Maariv": "https://www.maariv.co.il/rss/rssfeedsmivzakichadashot",
    "Mako": "https://storage.googleapis.com/mako-sitemaps/rssHomepage.xml",
}


def get_status(score: int) -> str:
    if score <= 10:  return "תישן טוב הלילה 😴"
    if score <= 25:  return "לך לישון, הכל בסדר"
    if score <= 40:  return "אפשר לנשום. בנתיים."
    if score <= 55:  return "תכין את הקיט, אבל אל תפנה את הבית"
    if score <= 70:  return "אולי תמלא את המיכל?"
    if score <= 85:  return "קנה טונה עכשיו!!!"
    return "📦 הכל לממ\"ד. עכשיו."


def fetch_headlines() -> list[dict]:
    """
    Fetches headlines from RSS feeds. Only includes headlines from the last CUTOFF_DAYS days.
    """
    results = []
    now = datetime.now(timezone.utc)
    cutoff = now - timedelta(days=CUTOFF_DAYS)
    
    for i, (feed_source, feed_url) in enumerate(RSS_FEEDS.items()):
        try:
            feed = feedparser.parse(feed_url)
            for entry in feed.entries[:10]:
                title = entry.get("title", "").strip()
                published_parsed = entry.get("published_parsed")
                
                if published_parsed:
                    # published_parsed is a time.struct_time, convert to datetime
                    pub_date = datetime(*published_parsed[:6], tzinfo=timezone.utc)
                    if pub_date < cutoff:
                        continue
                    if feed_source == "Walla":
                        pub_date = pub_date - timedelta(hours=1)  # Walla times are GMT

                if title:
                    results.append({
                        "id": f"{i}-{len(results)}", 
                        "text": title, 
                        "source": feed_source, 
                        "datetime": pub_date.isoformat() if published_parsed else ""
                    })
        except Exception as e:
            print(f"[Feed error] {feed_url}: {e}")
    return results


def calculate_time_ago(published_time: str) -> str:
    try:
        pub_date = datetime.fromisoformat(published_time)
        now = datetime.now(timezone.utc)
        diff = now - pub_date
        if diff < timedelta(minutes=1):
            return "עכשיו"
        if diff < timedelta(hours=1):
            return f"לפני {int(diff.total_seconds() // 60)} דקות"
        if diff < timedelta(days=1):
            return f"לפני {int(diff.total_seconds() // 3600)} שעות"
        return f"לפני {int(diff.total_seconds() // 86400)} ימים"
    except Exception as e:
        print(f"[Time parsing error] {e}")
        return "זמן לא ידוע"


def llm_score_headlines(headlines: list[dict]) -> list[dict]:
    """
    Scores headlines using Gemini LLM. Returns list of headlines with 'impact' field added
    """
    if not client:
        return []

    titles = "\n".join([f"{i+1}. {h['text']} ({calculate_time_ago(h.get('datetime', ''))})" for i, h in enumerate(headlines)])
    cached_headlines = load_cache().get("top_headlines") or []
    # Only include history that was actually generated by LLM
    # llm_history = [h for h in cached_headlines if h.get("is_llm", False)]
    history = []
    for i, h in enumerate(cached_headlines):
        text = h.get("text", "")
        impact = h.get("impact", "N/A")
        time_ago = calculate_time_ago(h.get("timestamp", ""))
        history.append(f"{i+1}. {text} (score: {impact}, time: {time_ago})")
    history = "\n".join(history) if history else ""
    
    prompt = f"""
אתה אנליסט מומחה לניתוח סנטימנט בטחוני בישראל. תפקידך לדרג כותרות חדשות לפי השפעתן על **'מדד הפאניקה הלאומי'**.

### סולם הדירוג (מ-10- עד 10+)
- [10-] (רגיעה מוחלטת/אופוריה): הסכם שלום היסטורי, פירוק תשתיות אויב באופן סופי, חיסול דרמטי של מנהיג אויב.
- [5- עד 9-]: תקיפות צה"ל באיראן, הצלחה טכנולוגית חסרת תקדים (לייזר מבצעי), פתיחת מיצרי הורמוז לכל המדינות, הצהרת הרגעה של ארה"ב ודו"צ יחד.
- [1- עד 4-]: יירוטים מוצלחים, חזרה לשגרה בערים נוספות, כותרות אופטימיות על הכלכלה.
- [0]: חדשות ניטרליות לחלוטין (מזג אוויר, ספורט, פטירת ידוענים מסיבות טבעיות, רכילות).
- [1+ עד 3+]: "רעש רקע" של מלחמה: איומים מילוליים של האויב, שיבושי GPS, תקלות טכניות בשירותים ציבוריים.
- [4+ עד 6+]: אירוע בטחוני מוגדר: נפילה בשטח פתוח, פצועים קל, אזעקות במרכז הארץ, פתיחת חזיתות נוספות.
- [7+ עד 9+]: אירוע קשה: הרוגים בקרב כוחותינו/אזרחים, פגיעה ישירה בבית, חדירת כלי טיס שלא יורט.
- [10+] (פאניקה לאומית): מתקפת פתע רחבה, פגיעה בתשתיות קריטיות (חשמל/מים/קשר) ארציות, אירוע רב נפגעים המוני.

### מצב נוכחי:  
אנחנו כרגע בהפסקת אש עם איראן אחרי לחימה של 38 ימים במסגרת מבצע "שאגת הארי" שבו תקפנו ביחד עם חיל האוויר של ארצות הברית באיראן. בינתיים הם עדיין סוגרים את מיצרי הורמוז, מה שמייקר את מחיר הנפט

### דירוגים קודמים:  
{history}

### הנחיות קריטיות:  
1. עיין ברשימת 'דירוגים קודמים'.
2. שמור על קונסיסטנטיות, אך שים לב לזמני הכותרות, למשל הודעה על שיגור רקטות לעבר ישראל מלפני שעתיים לא תהיה מאוד מלחיצה.
3. ידיעות צבע/פנאי/פטירה טבעית = 0.
4. "עצוב" אך לא "מפחיד" = 0.

### כותרות חדשות:  
{titles}

ענה בפורמט של רשימת מספרים מופרדים בפסיקים בלבד: 10,0,-5,7
"""
    try:
        response = client.models.generate_content(model=LLM, contents=prompt)
        raw = response.text.strip()
        scores = [int(x.strip()) for x in re.findall(r"-?\d+", raw)]
        for i, h in enumerate(headlines):
            if i < len(scores):
                h["impact"] = max(-10, min(10, scores[i]))
                h["is_llm"] = True
            else:
                # If LLM didn't return enough scores, we consider it a failure for consistency
                return []
        return headlines

    except exceptions.ResourceExhausted as e:
        print(f"[LLM rate limit] {e}")
        # Try to extract retry delay from error details if possible, otherwise default to 60s
        delay = 60
        try:
            # The error message often contains the retry delay in seconds
            match = re.search(r"retry in ([\d\.]+)s", str(e))
            if match:
                delay = float(match.group(1)) + 1
        except:
            pass
        
        print(f"Rate limited. Sleeping for {delay} seconds before retrying...")
        time.sleep(delay)
        raise e # Let update_mood_data catch and retry

    except Exception as e:
        print(f"[LLM error] {e} — will retry after sleep")
        time.sleep(60)
        raise e


def calculate_score(headlines: list[dict]) -> int:
    """
    Calculate overall mood score based on headline impacts
    Normalizes to a 0-100 scale where 0 is very calm and 100 is full panic
    """
    if not headlines:
        return 30
    total_impact = sum(h.get("impact", 0) for h in headlines)
    normalized = (total_impact + 100) / 200 * 100
    return max(0, min(100, int(normalized)))


def deduplicate_headlines(headlines: list[dict]) -> list[dict]:
    """
    Deduplicate headlines using LLM. Returns a list of unique headlines
    """
    if not client or not headlines:
        return headlines

    prompt = "אתה אלגוריתם מומחה לזיהוי כותרות חדשות דומות. קבל רשימת כותרות והחזר רק את הייחודיות ביותר, תוך הסרה של כותרות שנראות כמעט זהות או מתייחסות לאותו אירוע. הנה הכותרות:\n"
    for i, h in enumerate(headlines):
        prompt += f"{i}. {h['text']}\n"
    prompt += "\nהחזר את מספרי הכותרות הייחודיות בלבד (למשל: 0, 2, 5), מופרדים על ידי פסיקים."
    
    try:
        response = client.models.generate_content(model=LLM, contents=prompt)
        raw = response.text.strip()
        unique_indices = set(int(x.strip()) for x in re.findall(r"\d+", raw))
        return [h for i, h in enumerate(headlines) if i in unique_indices]
    except exceptions.ResourceExhausted as e:
        print(f"[Deduplication rate limit] {e}")
        # Just return original headlines if we can't deduplicate due to rate limit
        return headlines
    except Exception as e:
        print(f"[Deduplication error] {e} — returning original list")
        return headlines


def get_impactful_headline(headlines: list[dict], score: int) -> dict:
    """Get the headline that contributed the most to the score"""
    for h in headlines:
        impact = h.get("impact", 0)
        if score >= 50 and impact > 0:
            return h
        if score < 50 and impact < 0:
            return h
    return {}


def log_score(score: int, impactful_headline:dict) -> None:
    """
    Logs the current score and the most impactful headline for monitoring purposes
    """
    insert_daily_score(
        score=score,
        top_headline=impactful_headline.get("text", "N/A") if impactful_headline else "N/A",
        impact=impactful_headline.get("impact", 0) if impactful_headline else 0
    )


def log_headlines(headlines: list[dict]) -> None:
    """
    Logs the headlines to the database for monitoring and debugging purposes
    """
    # Insert only headlines that are unique for the same date
    insert_headlines(headlines)


async def update_mood_data():
    """
    Fetches headlines, scores them, and updates the cache with the latest mood data
    """
    print(f"[{datetime.now().isoformat()}] Starting mood update...", flush=True)
    raw_headlines = fetch_headlines()
    if not raw_headlines:
        print("No headlines fetched.")
        return

    scored_headlines = llm_score_headlines(raw_headlines)
    scored_headlines = deduplicate_headlines(scored_headlines)
    log_headlines(scored_headlines)
    
    if not scored_headlines:
        print("Scoring failed. Cache not updated.")
        return
    
    scored_headlines.sort(key=lambda h: abs(h.get("impact", 0)), reverse=True)
    top = scored_headlines[:20]
    total_score = calculate_score(scored_headlines)

    headlines_out = [
        {
            "id": str(i),
            "text": h["text"],
            "source": h["source"],
            "impact": h.get("impact", 0),
            "is_llm": h.get("is_llm", False),
            "timestamp": h.get("datetime", ""),
        }
        for i, h in enumerate(top)
    ]

    result = {
        "score": total_score,
        "status": get_status(total_score),
        "top_headlines": headlines_out,
        "last_updated": datetime.now().isoformat(),
    }
    impactful_headline = get_impactful_headline(scored_headlines, total_score)
    log_score(total_score, impactful_headline if impactful_headline else {})
    print(f"[{datetime.now().isoformat()}] Mood update completed: Score={total_score}, Headlines={len(headlines_out)}", flush=True)
    save_cache(result)


async def main():
    while True:
        try:
            await update_mood_data()
        except Exception as e:
            print(f"[Worker Error] {e}")
        await asyncio.sleep(UPDATE_INTERVAL)


if __name__ == "__main__":
    asyncio.run(main())
